apps/mesh/urls.py
from django.urls import path
from django.urls import re_path

from .views.editorial_views import AssignEditorView
from .views.editorial_views import EditorialDecisionCreateView
from .views.editorial_views import EditorialDecisionUpdateView
from .views.editorial_views import SendToReviewView
from .views.file_views import FileServingView
from .views.home import HomeView
from .views.journal_section_views import JournalSectionEditView
from .views.journal_section_views import JournalSectionListView
from .views.review_views import ReviewAcceptView
from .views.review_views import ReviewConfirmView
from .views.review_views import ReviewCreateView
from .views.review_views import ReviewDetails
from .views.review_views import ReviewFileAccessUpdate
from .views.review_views import ReviewSubmitView
from .views.role_views import RoleSwitchView
from .views.submission_edit_views import SubmissionAuthorView
from .views.submission_edit_views import SubmissionConfirmView
from .views.submission_edit_views import SubmissionCreateView
from .views.submission_edit_views import SubmissionResumeView
from .views.submission_edit_views import SubmissionUpdateView
from .views.submission_edit_views import SubmissionVersionCreateView
from .views.submission_edit_views import SubmissionVersionUpdateView
from .views.submission_views import ArchivedSubmissionListView
from .views.submission_views import SubmissionDetailsView
from .views.submission_views import SubmissionListView
from .views.submission_views import SubmissionLogView
from .views.user_views import CloseImpersonateSessionView
from .views.user_views import InitImpersonateSessionView
from .views.user_views import TokenLoginView

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    # Submission views
    path("submissions/", SubmissionListView.as_view(), name="submission_list"),
    path(
        "submissions/archived/",
        ArchivedSubmissionListView.as_view(),
        name="submission_list_archived",
    ),
    path("submissions/new/", SubmissionCreateView.as_view(), name="submission_create"),
    path("submissions/<int:pk>/update/", SubmissionUpdateView.as_view(), name="submission_update"),
    path("submissions/<int:pk>/resume/", SubmissionResumeView.as_view(), name="submission_resume"),
    path(
        "submission/<int:pk>/submit/confirm/",
        SubmissionConfirmView.as_view(),
        name="submission_confirm",
    ),
    path(
        "submissions/<int:pk>/authors/", SubmissionAuthorView.as_view(), name="submission_authors"
    ),
    path("submissions/<int:pk>/", SubmissionDetailsView.as_view(), name="submission_details"),
    path(
        "submissions/<int:submission_pk>/version/new/",
        SubmissionVersionCreateView.as_view(),
        name="submission_version_create",
    ),
    path(
        "versions/<int:pk>/",
        SubmissionVersionUpdateView.as_view(),
        name="submission_version_update",
    ),
    path("submissions/<int:pk>/log/", SubmissionLogView.as_view(), name="submission_log"),
    path("submissions/<int:pk>/editors/", AssignEditorView.as_view(), name="submission_editors"),
    # Review views
    path(
        "versions/<int:version_pk>/review/new/", ReviewCreateView.as_view(), name="review_create"
    ),
    path("reviews/<int:pk>/", ReviewDetails.as_view(), name="review_details"),
    path("reviews/<int:pk>/accept/", ReviewAcceptView.as_view(), name="review_accept"),
    path("reviews/<int:pk>/update/", ReviewSubmitView.as_view(), name="review_update"),
    path("reviews/<int:pk>/confirm/", ReviewConfirmView.as_view(), name="review_confirm"),
    path(
        "reviews/<int:pk>/files_access_update/",
        ReviewFileAccessUpdate.as_view(),
        name="review_file_access_update",
    ),
    # Editorial views
    path(
        "submissions/<int:pk>/to-review/",
        SendToReviewView.as_view(),
        name="submission_start_review_process",
    ),
    path(
        "submissions/<int:submission_pk>/decision/new/",
        EditorialDecisionCreateView.as_view(),
        name="editorial_decision_create",
    ),
    path(
        "decisions/<int:pk>/update/",
        EditorialDecisionUpdateView.as_view(),
        name="editorial_decision_update",
    ),
    # Role & user views
    path("role_switch/", RoleSwitchView.as_view(), name="role_switch"),
    path("impersonate/", InitImpersonateSessionView.as_view(), name="impersonate_init"),
    path("impersonate/close/", CloseImpersonateSessionView.as_view(), name="impersonate_close"),
    path("login-token/", TokenLoginView.as_view(), name="token_login"),
    # Submission journal_sections
    path(
        "journal_sections/",
        JournalSectionListView.as_view(),
        name="journal_section_list",
    ),
    path(
        "journal_sections/<int:pk>/update/",
        JournalSectionEditView.as_view(),
        name="submission_journal_section_update",
    ),
    # File views
    re_path(
        r"^files/(?P<file_identifier>[A-z0-9-_=]+)$",
        FileServingView.as_view(),
        name="serve_protected_file",
    ),
]

apps/mesh/models/review_models.py
from __future__ import annotations

import os
import re
from datetime import date
from enum import Enum
from enum import unique
from typing import TYPE_CHECKING
from typing import Self
from typing import TypeVar

from django.conf import settings
from django.db import models
from django.db.models.query import QuerySet
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from ..exceptions import ReviewStateError
from .base_models import BaseSubmittableModel
from .file_models import BaseFileWrapperModel
from .file_models import BaseModelWithFiles
from .submission_models import SubmissionLog
from .submission_models import SubmissionVersion

if TYPE_CHECKING:
    from ..roles.role_handler import RoleHandler


_T = TypeVar("_T", bound=models.Model)


@unique
class ReviewState(Enum):
    """
    Enum of the review statees.
    """

    # AWAITING ACCEPTANCE       Reviewer invited, waiting for reviewer to accept/decline
    #                           the review request.
    AWAITING_ACCEPTANCE = "awaiting_accept"
    # DECLINED                  Reviewer invited & declined the request.
    DECLINED = "declined"
    # PENDING                   Reviewer invited & accepted the request, waiting for
    #                           the review.
    PENDING = "pending"
    # SUBMITTED                 Reviewer invited, accepted the request and the review
    #                           was submitted.
    SUBMITTED = "submitted"


REVIEW_STATE_CHOICES = [
    (ReviewState.AWAITING_ACCEPTANCE.value, _("Waiting for acceptance")),
    (ReviewState.DECLINED.value, _("Declined")),
    (ReviewState.PENDING.value, _("Pending")),
    (ReviewState.SUBMITTED.value, _("Submitted")),
]


@unique
class RecommendationValue(Enum):
    """
    Enum of the recommendation values.
    Warning: the value of each state is used in CSS.
    """

    ACCEPTED = "accepted"
    REJECTED = "rejected"
    REVISION_REQUESTED = "rev_requested"
    RESUBMIT_SOMEWHERE_ELSE = "resubmit"


RECOMMENDATION_CHOICES = [
    (RecommendationValue.ACCEPTED.value, "Accept submission"),
    (RecommendationValue.REJECTED.value, "Decline submission"),
    (RecommendationValue.REVISION_REQUESTED.value, "Revision(s) required"),
    (RecommendationValue.RESUBMIT_SOMEWHERE_ELSE.value, "Re-submit somewhere else"),
]


class ReviewManager(models.Manager[_T]):
    def get_queryset(self) -> QuerySet[_T]:
        return (
            super()
            .get_queryset()
            .select_related(
                "created_by",
                "last_modified_by",
                "version",
                "version__submission",
                "version__submission__journal_section",
                "reviewer",
            )
            .prefetch_related("additional_files")
        )


class Review(BaseSubmittableModel, BaseModelWithFiles):
    file_fields_required = ["additional_files"]
    file_fields_deletable = ["additional_files"]

    version = models.ForeignKey(
        SubmissionVersion,
        on_delete=models.CASCADE,
        related_name="reviews",
        blank=True,
        help_text=_("Automatically filled on save"),
    )
    state = models.CharField(
        max_length=64,
        choices=REVIEW_STATE_CHOICES,
        default=ReviewState.AWAITING_ACCEPTANCE.value,
    )
    reviewer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    date_response_due = models.DateField(verbose_name=_("Response due date"))
    date_review_due = models.DateField(verbose_name=_("Review due date"))
    recommendation = models.CharField(
        max_length=64, choices=RECOMMENDATION_CHOICES, blank=False, null=True, default=""
    )
    accepted = models.BooleanField(
        verbose_name=_("Confirmation"),
        choices=[(True, _("Accept")), (False, _("Decline"))],
        null=True,
        blank=False,
    )
    date_accepted = models.DateTimeField(editable=False, null=True)
    # Optional message for the reviewer to be filled by the editor
    # when making a referee request.
    request_email = models.TextField(verbose_name=_("Request e-mail"), null=True, blank=True)
    # Optional message from the reviewer to the editor when accepting/declining the
    # referee request
    accept_comment = models.TextField(verbose_name=_("Accept comment"), null=True, blank=True)
    # Comment/message from the reviewer to the editor when filling the review form.
    comment = models.TextField(verbose_name=_("Review comment"), null=True, blank=True)

    objects: ReviewManager[Self] = ReviewManager()

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["version", "reviewer"], name="unique_reviewer_per_round"
            )
        ]

    def __str__(self) -> str:
        return f"Review: {self.reviewer} - {self.version}"

    @property
    def is_response_overdue(self) -> bool:
        return self.accepted is None and self.date_response_due < date.today()

    @property
    def is_report_overdue(self) -> bool:
        return self.is_response_overdue or (
            self.accepted is True
            and self.submitted is False
            and self.date_review_due < date.today()
        )

    @property
    def is_completed(self) -> bool:
        return self.accepted is False or self.submitted is True

    @property
    def is_editable(self) -> bool:
        return not self.submitted and self.version.review_open

    def accept(
        self,
        accept_value: bool,
        accept_comment: str | None,
        user,
        impersonate_data=None,
    ) -> None:
        if not self.is_editable:
            raise ReviewStateError("Trying to accept a non-editable review.")

        self._user = user  # type:ignore
        self.accepted = accept_value
        self.state = ReviewState.PENDING.value if accept_value else ReviewState.DECLINED.value
        self.date_accepted = timezone.now()
        self.accept_comment = accept_comment

        self.save()

        base_message = (
            "Referee request accepted by" if accept_value else "Referee request declined by"
        )

        SubmissionLog.add_message(
            self.version.submission,
            content=_(base_message) + f" {self.reviewer}",
            content_en=f"{base_message} {self.reviewer}",
            user=user,
            # impersonate_data=impersonate_data,
            significant=True,
        )

    @property
    def is_submittable(self) -> bool:
        return not self.is_completed and self.is_editable

    def submit(self, user) -> None:
        if not self.is_submittable:
            raise ReviewStateError("Trying to submit a non-editable review.")

        self._user = user  # type:ignore
        self.state = ReviewState.SUBMITTED.value
        self.submitted = True

        self.save()

        SubmissionLog.add_message(
            self.version.submission,
            content=_(f"Review for round #{self.version.number} submitted by")
            + f" {self.reviewer}",
            content_en=f"Review for round #{self.version.number} submitted by {self.reviewer}",
            user=user,
            # impersonate_data=impersonate_data,
            significant=True,
        )


class ReviewAdditionalFile(BaseFileWrapperModel):
    attached_to: models.ForeignKey[Review] = models.ForeignKey(
        Review, on_delete=models.CASCADE, related_name="additional_files"
    )
    author_access = models.BooleanField(default=False)

    @staticmethod
    def get_upload_path(instance: ReviewAdditionalFile, filename: str) -> str:
        return os.path.join(
            "submissions",
            str(instance.attached_to.version.submission.pk),
            "versions",
            str(instance.attached_to.version.number),
            "review",
            str(instance.attached_to.pk),
            filename,
        )

    @classmethod
    def reverse_file_path(cls, file_path: str) -> ReviewAdditionalFile | None:
        """
        Check first with a regex if the given path might match. This is not necessary
        but it saves us a DB query in case in doesn't match the path structure.
        """
        regex = "/".join(
            [
                "submissions",
                r"(?P<submission_pk>[0-9]+)",
                "versions",
                r"(?P<version_number>[0-9]+)",
                "review",
                r"(?P<review_pk>[0-9]+)",
                r"(?P<file_name>[^\/]+)$",
            ]
        )
        match = re.match(re.compile(regex), file_path)
        if not match:
            return None

        return cls._default_manager.filter(file=file_path).first()

    def check_access_right(self, role_handler: RoleHandler, right_code: str) -> bool:
        """
        This model is only editable by user role with edit rights on the submission.
        """
        if right_code == "read":
            return role_handler.check_global_rights("can_access_review", self.attached_to)

        elif right_code in ["delete"]:
            return role_handler.check_rights("can_edit_review", self.attached_to)

        return False

apps/mesh/templates/mesh/review/review_confirm.html
{% extends "mesh/forms/form_full_page.html" %}
{% load static i18n %}

{% block extra_css %}
{{ block.super }}
<link rel="stylesheet" href="{% static "mesh/css/components/table.css" %}">
{% endblock extra_css%}

{% block extra_js %}
{{ block.super }}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js" integrity="sha512-3gJwYpMe3QewGELv8k/BX9vcqhryRdzRMxVfq6ngyWXwo03GFEzjsUm8Q7RZcHPHksttq7/GFoxjCVUjkjvPdw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
{% endblock extra_js %}

{% block page_title %}
<span>
  {% translate "Confirm Review" %}
</span>
{% endblock page_title %}


{% block form_description %}
<div class="custom-form-description">
  <p>
    {% blocktranslate %}
    You are about to submit your review for the round {{ review_proxy.version.number }} of the submission
    {% endblocktranslate %}
    <a href="{% url "mesh:submission_details" pk=review_proxy.version.submission.pk %}">{{ review_proxy.version.submission.name|safe }}</a>
  </p>
  <p>
    {% translate "Please confirm that the below information is correct." %}
  </p>
  <div class="review-recap">
    {% comment %} Metadata {% endcomment %}
    <div class="mesh-page-content-section">
      <div class="section-title">
        {% translate "Data" %}
        <div class="section-separator"></div>
      </div>
      <div id="submission-recap-metadata" class="raw-data-display section-content">
        <div>
          {% translate "Recommendation" %}
        </div>
        <div>
          {{ review_proxy.get_recommendation_display }}
        </div>
        <div>
          {% translate "Review comment" %}
        </div>
        <div class="ckeditor-content">
          {{ review_proxy.comment|safe }}
        </div>
      </div>
    </div>
    {% comment %} Files {% endcomment %}
    <div class="mesh-page-content-section">
      <div class="section-title">
        {% translate "Files" %}
        <div class="section-separator"></div>
      </div>
      <div class="section-content">
        {% include "mesh/files_table.html" with files=review_files %}
      </div>
    </div>
  </div>
</div>
{% endblock form_description %}

apps/mesh/templates/mesh/review/review_details.html
{% extends "base.html" %}
{% load mesh_tags i18n static %}

{% block extra_css %}
{{ block.super }}
<link rel="stylesheet" href="{% static "mesh/css/components/table.css" %}">
<link rel="stylesheet" href="{% static "mesh/css/review_details.css" %}">
{% endblock extra_css%}

{% block extra_js %}
{{ block.super }}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js" integrity="sha512-3gJwYpMe3QewGELv8k/BX9vcqhryRdzRMxVfq6ngyWXwo03GFEzjsUm8Q7RZcHPHksttq7/GFoxjCVUjkjvPdw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
{% endblock extra_js %}

{% block main_content %}
<div id="mesh-page-journal_section">
  <div class="page-title-block">
    <div class="page-title">
      {% translate "Review details" %} - {{ review_proxy.version.submission.name|safe }}
    </div>
  </div>

  <div id="mesh-page-content">
    <div class="mesh-page-content-section">
      <div class="section-title">
        {% translate "REVIEW DATA" %}
        <div class="section-separator"></div>
      </div>
      <div id="review-data" class="raw-data-display section-content">
        <div>{% translate "Submission" %}</div>
        <div><a href="{% url "mesh:submission_details" pk=review_proxy.version.submission.pk %}">{{ review_proxy.version.submission.name|safe }}</a></div>

        <div>{% translate "Reviewer" %}</div>
        <div>{{ review_proxy.reviewer }}</div>

        <div>{% translate "Round" %}</div>
        <div>#{{ review_proxy.version.number }}</div>

        <div>{% translate "Status" %}</div>
        <div><span class="inline-badge">{{ review_proxy.get_state_display }}</span></div>

        <div>{% translate "Recommendation" %}</div>
        <div>
          {% if review_proxy.recommendation %}
          <span class="inline-badge recommendation {{ review_proxy.recommendation }}">{{ review_proxy.get_recommendation_display }}</span>
          {% endif %}
        </div>

        <div>
          {% translate "Files" %}
        </div>
        <div class="mesh-table-wrapper">
          {% if review_proxy.additional_files %}
          {% include "mesh/dataTable_config.html" %}
          {% check_rights role_handler "can_edit_review_file_right" review_proxy as can_edit_review_file_right %}
          {% if can_edit_review_file_right %}
          <form method="POST" action="{% url "mesh:review_file_access_update" pk=review_proxy.pk %}">
            {% csrf_token %}
          {% endif %}
            <table  id="table-review-files"
              class="mesh-table"
              data-searching="false"
              data-paging="false"
              data-info="false">
              <thead>
                <tr>
                  <th>{% translate "Name" %}</th>
                  <th class="author-access">{% translate "Author access" %}</th>
                </tr>
              </thead>
              <tbody>
              {% for file_wrapper in review_proxy.additional_files %}
              <tr>
                <td class="review-file">
                  <a href="{{ file_wrapper.get_file_url }}" target="_blank">{{ file_wrapper.name }}</a>
                  <i>{{ file_wrapper.file.size|filesizeformat }}</i>
                </td>
                <td class="author-access">
                  {% if file_wrapper.author_access %}
                  <div class="review-author-availability" data-tooltip="{% translate "Available to the author(s)" %}">
                    {% if edit_right %}
                    <input type="checkbox" name="{{ input_prefix }}{{ file_wrapper.pk }}" checked value="{{ input_value }}">
                    {% endif %}
                    <i class="fa-solid fa-user color-primary"></i>
                    <i class="fa-solid fa-circle-check color-success"></i>
                  </div>
                  {% else %}
                  <div class="review-author-availability" data-tooltip="{% translate "Not available to the author(s)" %}">
                    {% if edit_right %}
                    <input type="checkbox" name="{{ input_prefix }}{{ file_wrapper.pk }}" value="{{ input_value }}">
                    {% endif %}
                    <i class="fa-solid fa-user color-primary"></i>
                    <i class="fa-solid fa-circle-xmark color-error"></i>
                  </div>
                  {% endif %}
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        {% if can_edit_review_file_right %}
          <div class="form-buttons">
            <button type="submit">
              <i class="fa-solid fa-floppy-disk" aria-hidden="true"></i>
              {% translate "Save" %}
            </button>
          </div>
        </form>
        {% endif %}
        {% endif %}
        </div>

        <div>{% translate "Comment / Message" %}</div>
        <div class="ckeditor-content" >{% if review_proxy.comment %}{{ review_proxy.comment|safe }}{% endif %}</div>

        <div>{% translate "Accepted" %}</div>
        <div>
          {% if review_proxy.accepted %}
          <i class="fa-solid fa-circle-check"></i>
          {% elif review_proxy.accepted is False %}
          <i class="fa-solid fa-circle-xmark"></i>
          {% endif %}
        </div>

        <div>{% translate "Response date" %}</div>
        <div><i>{{  review_proxy.date_accepted|date:"DATE_FORMAT" }}</i></div>

        <div>{% translate "Response comment" %}</div>
        <div class="ckeditor-content" >{% if review_proxy.accept_comment %}{{ review_proxy.accept_comment|safe }}{% endif %}</div>

        <div>{% translate "Submitted" %}</div>
        <div>
          {% if review_proxy.submitted %}
          <i class="fa-solid fa-circle-check"></i>
          {% elif review_proxy.submited is False %}
          <i class="fa-solid fa-circle-xmark"></i>
          {% endif %}
        </div>

        <div>{% translate "Submitted on" %}</div>
        <div>{% if review_proxy.date_submitted %}<i>{{ review_proxy.date_submitted }}</i>{% endif %}</div>
      </div>
    </div>
    <div class="mesh-page-content-section">
      <div class="section-title">
        {% translate "REQUEST DATA" %}
        <div class="section-separator"></div>
      </div>
      <div id="review-metadata" class="raw-data-display section-content">
        <div>{% translate "Requested by" %}</div>
        <div>{{ review_proxy.created_by }}</div>

        <div>{% translate "Requested on" %}</div>
        <div><i>{{  review_proxy.date_created|date:"DATE_FORMAT" }}</i></div>

        <div>{% translate "Response due date" %}</div>
        <div><i>{{  review_proxy.date_response_due|date:"DATE_FORMAT" }}</i></div>

        <div>{% translate "Review due date" %}</div>
        <div><i>{{  review_proxy.date_review_due|date:"DATE_FORMAT" }}</i></div>

        <div>{% translate "Request e-mail" %}</div>
        <div>{% if review_proxy.request_email %}{{  review_proxy.request_email|safe }}{% endif %}</div>
      </div>
    </div>
  </div>
</div>
{% endblock main_content %}